#!/usr/bin/env python3
# This file was generated by an LLM.
"""Mutation sweep over include/tlm/stream.hpp.

For each mutant: patch stream.hpp, rebuild tm_tests, run ctest, restore the original.
KILLED means the build succeeded and at least one test failed, crashed or timed out.
SURVIVED means every test passed, so the suite does not pin that behaviour.
BUILD-FAIL means the mutant did not compile; it says nothing about the tests.
EQUIVALENT marks a mutant no input can distinguish from the original, with the reason. It is still
run, and reported as EQUIVALENT if it survives. If one is KILLED, the claim was wrong and it is
reported as an error.

Edits are keyed by 1-based line numbers of the unmodified file, and every edit asserts the text it
replaces, so the script stops instead of silently mutating the wrong thing after stream.hpp changes.

Usage: tools/mutate_stream.py [--build-dir build] [--filter SUBSTR] [--allow-dirty] [--list]
Exit status: 0 if no non-equivalent mutant survived, 1 if any did or an equivalent claim was
wrong, 2 on a setup problem.
"""

import argparse
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "include/tlm/stream.hpp"

# Edit = (line, text that must occur on that line, replacement for that text).
# A replacement of "" on a whole-line match deletes the statement but keeps line numbering.
Edit = tuple[int, str, str]


@dataclass
class Mutant:
    name: str
    edits: list[Edit]
    equivalent: str = ""  # why no input can tell this mutant from the original


def build_mutants() -> list[Mutant]:
    m: list[Mutant] = []

    def add(name: str, *edits: Edit, equivalent: str = "") -> None:
        m.append(Mutant(name, list(edits), equivalent))

    # 0007: Resync{error, ...} is only reachable for BadChecksum/MalformedFrame, whose detail is 0
    # (decoder.hpp, 0001), so Error{error.code} == error.
    detail_zero = "0007/0001: Resync codes carry detail 0, so dropping detail changes nothing"
    # 0007: the fallthrough runs only for an ErrorCode outside the named enumerators.
    unreachable = "0007: runs only for an ErrorCode outside the enumerators; no input produces one"
    # 0007: frame() sizes Found from byte 10 and decode()'s gates read the same byte.
    no_malformed = "0007: the stream cannot reach MalformedFrame, so which group it is in is unobservable"

    # --- each offset_ += line ------------------------------------------------------------------
    offset_lines = {
        45: ("found.length", "kResyncShift"),  # DecodedFrame
        52: ("kResyncShift", "found.length"),  # Resync, listed codes
        57: ("found.length", "kResyncShift"),  # skip Error
        62: ("kResyncShift", "found.length"),  # after the switch
        68: ("discard.count", "kResyncShift"),  # Discard
    }
    for ln, (amount, other) in offset_lines.items():
        stmt = f"offset_ += {amount};"
        eq = unreachable if ln == 62 else ""
        add(f"L{ln} offset_: delete", (ln, stmt, ""), equivalent=eq)
        add(f"L{ln} offset_: {amount} + 1", (ln, stmt, f"offset_ += {amount} + 1;"), equivalent=eq)
        add(f"L{ln} offset_: {amount} - 1", (ln, stmt, f"offset_ += {amount} - 1;"), equivalent=eq)
        add(f"L{ln} offset_: {amount} -> {other}", (ln, stmt, f"offset_ += {other};"), equivalent=eq)
        add(f"L{ln} offset_: += -> =", (ln, stmt, f"offset_ = {amount};"), equivalent=eq)
        add(f"L{ln} offset_: += -> -=", (ln, stmt, f"offset_ -= {amount};"), equivalent=eq)

    # --- each returned count / event payload -----------------------------------------------------
    for ln in (53, 63):
        ret = "return Resync{error, kResyncShift};"
        eq = unreachable if ln == 63 else ""
        add(f"L{ln} Resync count: 0", (ln, ret, "return Resync{error, 0};"), equivalent=eq)
        add(f"L{ln} Resync count: kResyncShift + 1", (ln, ret, "return Resync{error, kResyncShift + 1};"),
            equivalent=eq)
        add(f"L{ln} Resync count: kResyncShift - 1", (ln, ret, "return Resync{error, kResyncShift - 1};"),
            equivalent=eq)
        add(f"L{ln} Resync count: found.length", (ln, ret, "return Resync{error, found.length};"),
            equivalent=eq)
        add(f"L{ln} Resync error: code only", (ln, ret, "return Resync{Error{error.code}, kResyncShift};"),
            equivalent=eq or detail_zero)
    add("L58 skip Error: detail dropped", (58, "return error;", "return Error{error.code};"))
    add("L69 Discard count: 0", (69, "return discard;", "return Discard{0};"))
    add("L69 Discard count: + 1", (69, "return discard;", "return Discard{discard.count + 1};"))
    add("L69 Discard count: - 1", (69, "return discard;", "return Discard{discard.count - 1};"))

    # --- each case moved between the two groups ---------------------------------------------------
    # Labels sit on lines 50/51 (Resync group) and 54/55/56 (skip group); bodies stay put.
    resync = ["BadChecksum", "MalformedFrame"]
    skip = ["UnsupportedVersion", "UnknownMessageId", "WrongPayloadLength"]

    def regroup(r: list[str], s: list[str]) -> list[Edit]:
        def labels(codes: list[str]) -> str:
            return " ".join(f"case ErrorCode::{c}:" for c in codes)

        return [
            (50, "case ErrorCode::BadChecksum:", labels(r)),
            (51, "case ErrorCode::MalformedFrame:", ""),
            (54, "case ErrorCode::UnsupportedVersion:", labels(s)),
            (55, "case ErrorCode::UnknownMessageId:", ""),
            (56, "case ErrorCode::WrongPayloadLength:", ""),
        ]

    for code in resync:
        add(f"case {code}: Resync group -> skip group",
            *regroup([c for c in resync if c != code], skip + [code]),
            equivalent=no_malformed if code == "MalformedFrame" else "")
    for code in skip:
        add(f"case {code}: skip group -> Resync group",
            *regroup(resync + [code], [c for c in skip if c != code]))
    add("groups swapped", *regroup(skip, resync))

    # --- the Incomplete handler ------------------------------------------------------------------
    inc = "[](const Incomplete &) -> std::optional<Event> { return std::nullopt; }"
    cap = "[&](const Incomplete &) -> std::optional<Event>"
    add("L66 Incomplete: Discard{0}", (66, inc, f"{cap} {{ return Discard{{0}}; }}"))
    add("L66 Incomplete: Discard{rest.size()}", (66, inc, f"{cap} {{ return Discard{{rest.size()}}; }}"))
    add("L66 Incomplete: consume 1, nullopt", (66, inc, f"{cap} {{ offset_ += 1; return std::nullopt; }}"))
    add("L66 Incomplete: consume rest, nullopt",
        (66, inc, f"{cap} {{ offset_ += rest.size(); return std::nullopt; }}"))
    add("L66 Incomplete: Resync without consuming",
        (66, inc, f"{cap} {{ return Resync{{Error{{ErrorCode::MalformedFrame}}, kResyncShift}}; }}"))

    # --- rest.first(found.length) -----------------------------------------------------------------
    first = "decode(rest.first(found.length))"
    add("L42 first(found.length - 1)", (42, first, "decode(rest.first(found.length - 1))"))
    add("L42 first(found.length + 1)", (42, first, "decode(rest.first(found.length + 1))"))
    add("L42 whole rest", (42, first, "decode(rest)"))
    add("L42 last(found.length)", (42, first, "decode(rest.last(found.length))"))
    add("L42 first(kResyncShift)", (42, first, "decode(rest.first(kResyncShift))"))

    # --- the line(s) after the switch -------------------------------------------------------------
    add("L62-63 fallthrough: return error unconsumed",
        (62, "offset_ += kResyncShift;", ""), (63, "return Resync{error, kResyncShift};", "return error;"),
        equivalent=unreachable)
    add("L62-63 fallthrough: skip frame as Error",
        (62, "offset_ += kResyncShift;", "offset_ += found.length;"),
        (63, "return Resync{error, kResyncShift};", "return error;"), equivalent=unreachable)
    add("L62-63 fallthrough: nullopt",
        (62, "offset_ += kResyncShift;", ""), (63, "return Resync{error, kResyncShift};", "return std::nullopt;"),
        equivalent=unreachable)
    add("L62-63 fallthrough: nullopt after consuming",
        (63, "return Resync{error, kResyncShift};", "return std::nullopt;"), equivalent=unreachable)

    # --- extras: the lines around the ones asked for -----------------------------------------------
    add("L38 rest: subspan(0)", (38, "data_.subspan(offset_)", "data_.subspan(0)"))
    add("L38 rest: subspan(offset_ + 1)", (38, "data_.subspan(offset_)", "data_.subspan(offset_ + 1)"))
    add("L75 consumed(): 0", (75, "return offset_;", "return 0;"))
    add("L75 consumed(): offset_ + 1", (75, "return offset_;", "return offset_ + 1;"))
    add("L75 consumed(): offset_ - 1", (75, "return offset_;", "return offset_ - 1;"))
    return m


def apply(original: str, mutant: Mutant) -> str:
    lines = original.split("\n")
    for ln, old, new in mutant.edits:
        if ln > len(lines) or old not in lines[ln - 1]:
            raise SystemExit(
                f"stream.hpp no longer matches mutant '{mutant.name}': line {ln} should contain "
                f"{old!r} but is {lines[ln - 1] if ln <= len(lines) else '<past EOF>'!r}. "
                "Update build_mutants()."
            )
        lines[ln - 1] = lines[ln - 1].replace(old, new, 1)
    return "\n".join(lines)


_last_build_end = 0.0


def run(cmd: list[str], timeout: int) -> subprocess.CompletedProcess[str]:
    global _last_build_end
    try:
        return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout, check=False)
    finally:
        _last_build_end = time.time()


def write_header(text: str) -> None:
    """Write stream.hpp in a later wall-clock second than the last build finished.

    Make 3.81 (macOS /usr/bin/make) compares mtimes at one-second resolution, so a header written in
    the same second as the object it feeds looks up to date and the previous mutant gets tested again.
    """
    while int(time.time()) <= int(_last_build_end):
        time.sleep(0.05)
    TARGET.write_text(text)


def failing_tests(ctest_output: str) -> list[str]:
    names = re.findall(r"^\s*\d+ - (\S+) \(([^)]*)\)", ctest_output, re.MULTILINE)
    return [f"{n} [{why}]" for n, why in names]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--build-dir", default="build")
    ap.add_argument("--filter", default="", help="only run mutants whose name contains this")
    ap.add_argument("--allow-dirty", action="store_true", help="run although stream.hpp differs from HEAD")
    ap.add_argument("--list", action="store_true", help="print the mutants and exit")
    ap.add_argument("--test-timeout", type=int, default=10, help="per-test ctest timeout, seconds")
    args = ap.parse_args()

    mutants = [mu for mu in build_mutants() if args.filter in mu.name]
    if args.list:
        for i, mu in enumerate(mutants, 1):
            print(f"{i:3}  {mu.name}")
        return 0

    original = TARGET.read_text()
    dirty = subprocess.run(["git", "diff", "--quiet", "--", str(TARGET)], cwd=ROOT).returncode != 0
    if dirty and not args.allow_dirty:
        print("stream.hpp has uncommitted changes; a crashed earlier run may have left a mutant "
              "behind. Inspect it, or pass --allow-dirty.", file=sys.stderr)
        return 2

    build_dir = (ROOT / args.build_dir).resolve()
    build = ["cmake", "--build", str(build_dir), "--target", "tm_tests", "-j8"]
    test = ["ctest", "--test-dir", str(build_dir), "--timeout", str(args.test_timeout),
            "-j8", "--output-on-failure"]

    backup_dir = Path(tempfile.mkdtemp(prefix="stream-mutants-"))
    backup = backup_dir / "stream.hpp"
    shutil.copy2(TARGET, backup)

    def restore() -> None:
        write_header(backup.read_text())

    def on_signal(signum: int, _frame: object) -> None:
        shutil.copy2(backup, TARGET)
        sys.exit(128 + signum)

    signal.signal(signal.SIGINT, on_signal)
    signal.signal(signal.SIGTERM, on_signal)

    results: list[tuple[str, str, str]] = []  # (status, name, detail)
    try:
        write_header(original)
        if run(build, 900).returncode != 0 or run(test, 300).returncode != 0:
            print("Baseline is not green; fix that before sweeping.", file=sys.stderr)
            return 2

        for i, mu in enumerate(mutants, 1):
            write_header(apply(original, mu))
            try:
                b = run(build, 900)
                if b.returncode != 0:
                    status, detail = "BUILD-FAIL", ""
                else:
                    t = run(test, 300)
                    if t.returncode == 0:
                        status, detail = "SURVIVED", ""
                    else:
                        status = "KILLED"
                        tests = failing_tests(t.stdout)
                        detail = ", ".join(tests[:3]) + (f" (+{len(tests) - 3} more)" if len(tests) > 3 else "")
            except subprocess.TimeoutExpired:
                status, detail = "KILLED", "(whole-run timeout)"
            finally:
                restore()
            if mu.equivalent and status == "SURVIVED":
                status, detail = "EQUIVALENT", mu.equivalent
            elif mu.equivalent and status == "KILLED":
                status, detail = "WRONG-EQUIV", f"marked equivalent ({mu.equivalent}) but killed by {detail}"
            results.append((status, mu.name, detail))
            print(f"[{i:3}/{len(mutants)}] {status:<10} {mu.name}" + (f"  <- {detail}" if detail else ""),
                  flush=True)
    finally:
        restore()
        shutil.rmtree(backup_dir, ignore_errors=True)

    # Leave the build tree matching the restored header.
    run(build, 900)

    killed = [r for r in results if r[0] == "KILLED"]
    survived = [r for r in results if r[0] == "SURVIVED"]
    equivalent = [r for r in results if r[0] == "EQUIVALENT"]
    wrong = [r for r in results if r[0] == "WRONG-EQUIV"]
    broken = [r for r in results if r[0] == "BUILD-FAIL"]
    scored = len(killed) + len(survived)
    print(f"\n{len(results)} mutants: {len(killed)} killed, {len(survived)} survived, "
          f"{len(equivalent)} equivalent, {len(broken)} did not compile"
          + (f"; score {100 * len(killed) / scored:.0f}% of the {scored} non-equivalent that compiled"
             if scored else ""))
    for label, rows in (("SURVIVED", survived), ("WRONG-EQUIV (claim is false, fix the mutant list)", wrong),
                        ("BUILD-FAIL", broken)):
        if rows:
            print(f"\n{label}:")
            for _, name, _ in rows:
                print(f"  {name}")
    if equivalent:
        print("\nEQUIVALENT (excluded from the score):")
        for _, name, why in equivalent:
            print(f"  {name}  -- {why}")
    return 1 if survived or wrong else 0


if __name__ == "__main__":
    sys.exit(main())
